/* ═══════════════════════════════════════════════════════════════════
   ReguLens — Country → First-Level Administrative Division Metadata
   One centralized source for country codes, division labels, and
   complete administrative-division lists. Shared by server and browser.
   ═══════════════════════════════════════════════════════════════════ */

"use strict";

/**
 * COUNTRY_REGIONS
 *
 * Keyed by ISO 3166-1 alpha-2 code (lowercase).
 * Each entry:
 *   name        – Country name (English)
 *   flag        – Flag emoji
 *   divisionLabel – Label for the first-level admin division (English)
 *   divisions   – Array of division names (complete, accurate list)
 *   noDivisions – If true, country has no meaningful state/region subdivision
 */

const COUNTRY_REGIONS = {
  in: {
    name: "India",
    flag: "🇮🇳",
    divisionLabel: "State / Union Territory",
    divisions: [
      "Andhra Pradesh",
      "Arunachal Pradesh",
      "Assam",
      "Bihar",
      "Chhattisgarh",
      "Goa",
      "Gujarat",
      "Haryana",
      "Himachal Pradesh",
      "Jharkhand",
      "Karnataka",
      "Kerala",
      "Madhya Pradesh",
      "Maharashtra",
      "Manipur",
      "Meghalaya",
      "Mizoram",
      "Nagaland",
      "Odisha",
      "Punjab",
      "Rajasthan",
      "Sikkim",
      "Tamil Nadu",
      "Telangana",
      "Tripura",
      "Uttar Pradesh",
      "Uttarakhand",
      "West Bengal",
      "Andaman and Nicobar Islands",
      "Chandigarh",
      "Dadra and Nagar Haveli and Daman and Diu",
      "Delhi",
      "Jammu and Kashmir",
      "Ladakh",
      "Lakshadweep",
      "Puducherry",
    ],
  },
  us: {
    name: "United States",
    flag: "🇺🇸",
    divisionLabel: "State",
    divisions: [
      "Alabama",
      "Alaska",
      "Arizona",
      "Arkansas",
      "California",
      "Colorado",
      "Connecticut",
      "Delaware",
      "Florida",
      "Georgia",
      "Hawaii",
      "Idaho",
      "Illinois",
      "Indiana",
      "Iowa",
      "Kansas",
      "Kentucky",
      "Louisiana",
      "Maine",
      "Maryland",
      "Massachusetts",
      "Michigan",
      "Minnesota",
      "Mississippi",
      "Missouri",
      "Montana",
      "Nebraska",
      "Nevada",
      "New Hampshire",
      "New Jersey",
      "New Mexico",
      "New York",
      "North Carolina",
      "North Dakota",
      "Ohio",
      "Oklahoma",
      "Oregon",
      "Pennsylvania",
      "Rhode Island",
      "South Carolina",
      "South Dakota",
      "Tennessee",
      "Texas",
      "Utah",
      "Vermont",
      "Virginia",
      "Washington",
      "West Virginia",
      "Wisconsin",
      "Wyoming",
      "District of Columbia",
    ],
  },
  uk: {
    name: "United Kingdom",
    flag: "🇬🇧",
    divisionLabel: "Country / Region",
    divisions: [
      "England",
      "Scotland",
      "Wales",
      "Northern Ireland",
    ],
  },
  ae: {
    name: "UAE",
    flag: "🇦🇪",
    divisionLabel: "Emirate",
    divisions: [
      "Abu Dhabi",
      "Ajman",
      "Dubai",
      "Fujairah",
      "Ras Al Khaimah",
      "Sharjah",
      "Umm Al Quwain",
    ],
  },
  de: {
    name: "Germany",
    flag: "🇩🇪",
    divisionLabel: "State / Bundesland",
    divisions: [
      "Baden-Württemberg",
      "Bavaria",
      "Berlin",
      "Brandenburg",
      "Bremen",
      "Hamburg",
      "Hesse",
      "Lower Saxony",
      "Mecklenburg-Vorpommern",
      "North Rhine-Westphalia",
      "Rhineland-Palatinate",
      "Saarland",
      "Saxony",
      "Saxony-Anhalt",
      "Schleswig-Holstein",
      "Thuringia",
    ],
  },
  sg: {
    name: "Singapore",
    flag: "🇸🇬",
    divisionLabel: "Region",
    noDivisions: true,
    divisions: [],
  },
  au: {
    name: "Australia",
    flag: "🇦🇺",
    divisionLabel: "State / Territory",
    divisions: [
      "Australian Capital Territory",
      "New South Wales",
      "Northern Territory",
      "Queensland",
      "South Australia",
      "Tasmania",
      "Victoria",
      "Western Australia",
    ],
  },
  ca: {
    name: "Canada",
    flag: "🇨🇦",
    divisionLabel: "Province / Territory",
    divisions: [
      "Alberta",
      "British Columbia",
      "Manitoba",
      "New Brunswick",
      "Newfoundland and Labrador",
      "Northwest Territories",
      "Nova Scotia",
      "Nunavut",
      "Ontario",
      "Prince Edward Island",
      "Quebec",
      "Saskatchewan",
      "Yukon",
    ],
  },
  jp: {
    name: "Japan",
    flag: "🇯🇵",
    divisionLabel: "Prefecture",
    divisions: [
      "Aichi",
      "Akita",
      "Aomori",
      "Chiba",
      "Ehime",
      "Fukui",
      "Fukuoka",
      "Fukushima",
      "Gifu",
      "Gunma",
      "Hiroshima",
      "Hokkaido",
      "Hyogo",
      "Ibaraki",
      "Ishikawa",
      "Iwate",
      "Kagawa",
      "Kagoshima",
      "Kanagawa",
      "Kochi",
      "Kumamoto",
      "Kyoto",
      "Mie",
      "Miyagi",
      "Miyazaki",
      "Nagano",
      "Nagasaki",
      "Nara",
      "Niigata",
      "Oita",
      "Okayama",
      "Okinawa",
      "Osaka",
      "Saga",
      "Saitama",
      "Shiga",
      "Shimane",
      "Shizuoka",
      "Tochigi",
      "Tokushima",
      "Tokyo",
      "Tottori",
      "Toyama",
      "Wakayama",
      "Yamagata",
      "Yamaguchi",
      "Yamanashi",
    ],
  },
  eu: {
    name: "European Union",
    flag: "🇪🇺",
    divisionLabel: "Member State",
    divisions: [
      "Austria",
      "Belgium",
      "Bulgaria",
      "Croatia",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Estonia",
      "Finland",
      "France",
      "Germany",
      "Greece",
      "Hungary",
      "Ireland",
      "Italy",
      "Latvia",
      "Lithuania",
      "Luxembourg",
      "Malta",
      "Netherlands",
      "Poland",
      "Portugal",
      "Romania",
      "Slovakia",
      "Slovenia",
      "Spain",
      "Sweden",
    ],
  },
  fr: {
    name: "France",
    flag: "🇫🇷",
    divisionLabel: "Region",
    divisions: [
      "Auvergne-Rhône-Alpes",
      "Bourgogne-Franche-Comté",
      "Brittany",
      "Centre-Val de Loire",
      "Corsica",
      "Grand Est",
      "Hauts-de-France",
      "Île-de-France",
      "Normandy",
      "Nouvelle-Aquitaine",
      "Occitanie",
      "Pays de la Loire",
      "Provence-Alpes-Côte d'Azur",
    ],
  },
  cn: {
    name: "China",
    flag: "🇨🇳",
    divisionLabel: "Province / Autonomous Region / Municipality",
    divisions: [
      "Anhui",
      "Beijing",
      "Chongqing",
      "Fujian",
      "Gansu",
      "Guangdong",
      "Guangxi",
      "Guizhou",
      "Hainan",
      "Hebei",
      "Heilongjiang",
      "Henan",
      "Hubei",
      "Hunan",
      "Inner Mongolia",
      "Jiangsu",
      "Jiangxi",
      "Jilin",
      "Liaoning",
      "Ningxia",
      "Qinghai",
      "Shaanxi",
      "Shandong",
      "Shanghai",
      "Shanxi",
      "Sichuan",
      "Taiwan",
      "Tianjin",
      "Tibet",
      "Xinjiang",
      "Yunnan",
      "Zhejiang",
      "Hong Kong",
      "Macau",
    ],
  },
  br: {
    name: "Brazil",
    flag: "🇧🇷",
    divisionLabel: "State",
    divisions: [
      "Acre",
      "Alagoas",
      "Amapá",
      "Amazonas",
      "Bahia",
      "Ceará",
      "Distrito Federal",
      "Espírito Santo",
      "Goiás",
      "Maranhão",
      "Mato Grosso",
      "Mato Grosso do Sul",
      "Minas Gerais",
      "Pará",
      "Paraíba",
      "Paraná",
      "Pernambuco",
      "Piauí",
      "Rio de Janeiro",
      "Rio Grande do Norte",
      "Rio Grande do Sul",
      "Rondônia",
      "Roraima",
      "Santa Catarina",
      "São Paulo",
      "Sergipe",
      "Tocantins",
    ],
  },
  kr: {
    name: "South Korea",
    flag: "🇰🇷",
    divisionLabel: "Province / Metropolitan City",
    divisions: [
      "Busan",
      "Chungcheongbuk-do",
      "Chungcheongnam-do",
      "Daegu",
      "Daejeon",
      "Gangwon-do",
      "Gwangju",
      "Gyeonggi-do",
      "Gyeongsangbuk-do",
      "Gyeongsangnam-do",
      "Incheon",
      "Jeju",
      "Jeollabuk-do",
      "Jeollanam-do",
      "Sejong",
      "Seoul",
      "Ulsan",
    ],
  },
  sa: {
    name: "Saudi Arabia",
    flag: "🇸🇦",
    divisionLabel: "Region / Province",
    divisions: [
      "Al Bahah",
      "Al Jawf",
      "Al Madinah",
      "Al Qassim",
      "Asir",
      "Eastern Province",
      "Ha'il",
      "Jizan",
      "Makkah",
      "Najran",
      "Northern Borders",
      "Riyadh",
      "Tabuk",
    ],
  },
  mx: {
    name: "Mexico",
    flag: "🇲🇽",
    divisionLabel: "State",
    divisions: [
      "Aguascalientes",
      "Baja California",
      "Baja California Sur",
      "Campeche",
      "Chiapas",
      "Chihuahua",
      "Ciudad de México",
      "Coahuila",
      "Colima",
      "Durango",
      "Guanajuato",
      "Guerrero",
      "Hidalgo",
      "Jalisco",
      "México",
      "Michoacán",
      "Morelos",
      "Nayarit",
      "Nuevo León",
      "Oaxaca",
      "Puebla",
      "Querétaro",
      "Quintana Roo",
      "San Luis Potosí",
      "Sinaloa",
      "Sonora",
      "Tabasco",
      "Tamaulipas",
      "Tlaxcala",
      "Veracruz",
      "Yucatán",
      "Zacatecas",
    ],
  },
  it: {
    name: "Italy",
    flag: "🇮🇹",
    divisionLabel: "Region",
    divisions: [
      "Abruzzo",
      "Aosta Valley",
      "Apulia",
      "Basilicata",
      "Calabria",
      "Campania",
      "Emilia-Romagna",
      "Friuli Venezia Giulia",
      "Lazio",
      "Liguria",
      "Lombardy",
      "Marche",
      "Molise",
      "Piedmont",
      "Sardinia",
      "Sicily",
      "Trentino-Alto Adige",
      "Tuscany",
      "Umbria",
      "Veneto",
    ],
  },
  es: {
    name: "Spain",
    flag: "🇪🇸",
    divisionLabel: "Autonomous Community",
    divisions: [
      "Andalusia",
      "Aragon",
      "Asturias",
      "Balearic Islands",
      "Basque Country",
      "Canary Islands",
      "Cantabria",
      "Castilla-La Mancha",
      "Castile and León",
      "Catalonia",
      "Extremadura",
      "Galicia",
      "La Rioja",
      "Madrid",
      "Murcia",
      "Navarre",
      "Valencia",
      "Ceuta",
      "Melilla",
    ],
  },
  nl: {
    name: "Netherlands",
    flag: "🇳🇱",
    divisionLabel: "Province",
    divisions: [
      "Drenthe",
      "Flevoland",
      "Friesland",
      "Gelderland",
      "Groningen",
      "Limburg",
      "North Brabant",
      "North Holland",
      "Overijssel",
      "Utrecht",
      "Zeeland",
      "South Holland",
    ],
  },
  se: {
    name: "Sweden",
    flag: "🇸🇪",
    divisionLabel: "County",
    divisions: [
      "Stockholm County",
      "Västra Götaland County",
      "Skåne County",
      "Östergötland County",
      "Uppsala County",
      "Västerbotten County",
      "Norrbotten County",
      "Jönköping County",
      "Kalmar County",
      "Gävleborg County",
      "Dalarna County",
      "Halland County",
      "Västmanland County",
      "Örebro County",
      "Västernorrland County",
      "Jämtland County",
      "Kronoberg County",
      "Gotland County",
      "Blekinge County",
      "Södermanland County",
    ],
  },
  ch: {
    name: "Switzerland",
    flag: "🇨🇭",
    divisionLabel: "Canton",
    divisions: [
      "Aargau",
      "Appenzell Ausserrhoden",
      "Appenzell Innerrhoden",
      "Basel-Landschaft",
      "Basel-Stadt",
      "Bern",
      "Fribourg",
      "Geneva",
      "Glarus",
      "Graubünden",
      "Jura",
      "Lucerne",
      "Neuchâtel",
      "Nidwalden",
      "Obwalden",
      "Schaffhausen",
      "Schwyz",
      "Solothurn",
      "St. Gallen",
      "Thurgau",
      "Ticino",
      "Uri",
      "Valais",
      "Vaud",
      "Zug",
      "Zurich",
    ],
  },
  ng: {
    name: "Nigeria",
    flag: "🇳🇬",
    divisionLabel: "State",
    divisions: [
      "Abia",
      "Adamawa",
      "Akwa Ibom",
      "Anambra",
      "Bauchi",
      "Bayelsa",
      "Benue",
      "Borno",
      "Cross River",
      "Delta",
      "Ebonyi",
      "Edo",
      "Ekiti",
      "Enugu",
      "FCT",
      "Gombe",
      "Imo",
      "Jigawa",
      "Kaduna",
      "Kano",
      "Katsina",
      "Kebbi",
      "Kogi",
      "Kwara",
      "Lagos",
      "Nasarawa",
      "Niger",
      "Ogun",
      "Ondo",
      "Osun",
      "Oyo",
      "Plateau",
      "Rivers",
      "Sokoto",
      "Taraba",
      "Yobe",
      "Zamfara",
    ],
  },
  id: {
    name: "Indonesia",
    flag: "🇮🇩",
    divisionLabel: "Province",
    divisions: [
      "Aceh",
      "Bali",
      "Banten",
      "Bengkulu",
      "Central Java",
      "Central Kalimantan",
      "Central Sulawesi",
      "East Java",
      "East Kalimantan",
      "East Nusa Tenggara",
      "Gorontalo",
      "Jakarta",
      "Jambi",
      "Lampung",
      "Maluku",
      "North Kalimantan",
      "North Maluku",
      "North Sulawesi",
      "North Sumatra",
      "Papua",
      "Riau",
      "South Kalimantan",
      "South Sulawesi",
      "South Sumatra",
      "Southeast Sulawesi",
      "West Java",
      "West Kalimantan",
      "West Nusa Tenggara",
      "West Papua",
      "West Sulawesi",
      "West Sumatra",
      "Yogyakarta",
    ],
  },
  th: {
    name: "Thailand",
    flag: "🇹🇭",
    divisionLabel: "Province",
    divisions: [
      "Bangkok",
      "Chiang Mai",
      "Chonburi",
      "Nonthaburi",
      "Chiang Rai",
      "Nakhon Ratchasima",
      "Phuket",
      "Ayutthaya",
      "Chachoengsao",
      "Lampang",
      "Nakhon Si Thammarat",
      "Rayong",
      "Khon Kaen",
      "Surat Thani",
      "Pathum Thani",
      "Samut Prakan",
      "Chiang Mai",
      "Hat Yai",
      "Udon Thani",
      "Ubon Ratchathani",
    ],
  },
  vn: {
    name: "Vietnam",
    flag: "🇻🇳",
    divisionLabel: "Province / City",
    divisions: [
      "Hanoi",
      "Ho Chi Minh City",
      "Da Nang",
      "Hai Phong",
      "Can Tho",
      "An Giang",
      "Ba Ria-Vung Tau",
      "Bac Giang",
      "Bac Kan",
      "Bac Lieu",
      "Bac Ninh",
      "Ben Tre",
      "Binh Dinh",
      "Binh Duong",
      "Binh Phuoc",
      "Binh Thuan",
      "Ca Mau",
      "Cao Bang",
      "Dak Lak",
      "Dak Nong",
      "Dien Bien",
      "Dong Nai",
      "Dong Thap",
      "Gia Lai",
      "Ha Giang",
      "Ha Nam",
      "Ha Tinh",
      "Hai Duong",
      "Hoa Binh",
      "Hung Yen",
      "Khanh Hoa",
      "Kien Giang",
      "Kon Tum",
      "Lai Chau",
      "Lam Dong",
      "Lang Son",
      "Lao Cai",
      "Long An",
      "Nam Dinh",
      "Nghe An",
      "Ninh Binh",
      "Ninh Thuan",
      "Phu Tho",
      "Phu Yen",
      "Quang Binh",
      "Quang Nam",
      "Quang Ngai",
      "Quang Ninh",
      "Quang Tri",
      "Soc Trang",
      "Son La",
      "Tay Ninh",
      "Thai Binh",
      "Thai Nguyen",
      "Thanh Hoa",
      "Thua Thien-Hue",
      "Tien Giang",
      "Tra Vinh",
      "Tuyen Quang",
      "Vinh Long",
      "Vinh Phuc",
      "Yen Bai",
    ],
  },
  my: {
    name: "Malaysia",
    flag: "🇲🇾",
    divisionLabel: "State / Federal Territory",
    divisions: [
      "Johor",
      "Kedah",
      "Kelantan",
      "Malacca",
      "Negeri Sembilan",
      "Pahang",
      "Penang",
      "Perak",
      "Perlis",
      "Sabah",
      "Sarawak",
      "Selangor",
      "Terengganu",
      "Kuala Lumpur",
      "Putrajaya",
      "Labuan",
    ],
  },
  ph: {
    name: "Philippines",
    flag: "🇵🇭",
    divisionLabel: "Region",
    divisions: [
      "BARMM",
      "Caraga",
      "Cordillera Administrative Region",
      "Ilocos Region",
      "Cagayan Valley",
      "Central Luzon",
      "Calabarzon",
      "Mimaropa",
      "Bicol Region",
      "Western Visayas",
      "Central Visayas",
      "Eastern Visayas",
      "Zamboanga Peninsula",
      "Northern Mindanao",
      "Davao Region",
      "Soccsksargen",
      "National Capital Region",
    ],
  },
};

/* ── helper functions ── */

function getCountryRegion(countryCode) {
  if (!countryCode) return null;
  const key = String(countryCode).toLowerCase().trim();
  return COUNTRY_REGIONS[key] || null;
}

function validateRegion(countryCode, regionName) {
  if (!countryCode) return false;
  const meta = getCountryRegion(countryCode);
  if (!meta) return false;
  if (meta.noDivisions) return true;
  if (!regionName) return false;
  return meta.divisions.some(
    (d) => d.toLowerCase() === String(regionName).toLowerCase().trim()
  );
}

function getNormalizedRegion(countryCode, regionName) {
  if (!countryCode || !regionName) return regionName || "";
  const meta = getCountryRegion(countryCode);
  if (!meta || meta.noDivisions) return regionName || "";
  const target = String(regionName).toLowerCase().trim();
  const match = meta.divisions.find((d) => d.toLowerCase() === target);
  return match || regionName;
}

module.exports = {
  COUNTRY_REGIONS,
  getCountryRegion,
  validateRegion,
  getNormalizedRegion,
};
